name: CI - Build and Test Service

on: [ push, pull_request ]

jobs:
  service-tests:
    name: "Test Service"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Build and run
      run: make dev

    - name: Run Tests
      run: make run-tests

    - name: Run Lint
      run: make lint

  devops-linters:
    name: "Lint DevOps"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Download shellcheck
      run: apt-get install -y shellcheck

    - name: Run shellcheck
      run: make lint-devops-shell-scripts

    - name: Run hadolint
      run: make lint-devops-dockerfiles
